### ISSUE TITLE
problems with holonix release in lib3h release 0.0.13

### ISSUE THREAD

**Issue by zippy** [holochain/holonix-archive#100]
in trying to cut a release of lib3h (0.0.13) We had problems using `hn-release-cut`.
It failed on us at the crates.io login stage.  Even though we had both logged in, and had a token in the `~/.cargo/credentials`  in it still failed at that point.   
I think this maybe my fault because I had previous updated lib3h to holonix 36, but I'm guessing I didn't do all the right things to the [default.nix](https://github.com/holochain/lib3h/blob/develop/default.nix) file.  
For example, that file was missing the ` ++ holonix.shell.buildInputs` line which I needed to even get the basic `hn` commands.

**Comment by thedavidmeister** [comment]
@zippy it's working for me, although i'm not an owner of all the crates so i end up getting errors

note that `~/.cargo/credentials` is not relevant because `$CARGO_HOME` will be set to the repo

run `cargo login` from inside a nix shell for the repo you'd like to release and it will put credentials in the local cargo home

also note that you're correct in adding the extra build inputs for `holonix.shell` i think we broke that earlier in montreal trying to avoid the Qt stuff (that has been removed anyway)
